MAIN_WINDOW_SIZE = "1400x900"
MAIN_WINDOW_TITLE = "I Wany My MTV - Playlist Maker"

LABELFRAME_UPPER_SIZE = {
    "width": 500,
    "height": 100
}
LABELFRAME_UPPER_TEXT = "Enter date:"
SPINBOX_DAY_VALUES = [str("{:02d}").format(number) for number in range(1, 32)]
SPINBOX_MONTH_VALUES = [str("{:02d}").format(number) for number in range(1, 13)]
LABELFRAME_UPPER_SPACER_WIDTH = 950
SCRAPE_BILLBOARD_BUTTON_TEXT = "Scrape Billboard"
SCRAPE_BILLBOARD_BUTTON_WIDTH = 12
HELP_BUTTON_IMAGE_SIZE = (14, 14)

DATE_ENTRY_NOT_VALID_WINDOW_TITLE = "Warning!"
DATE_ENTRY_NOT_VALID_WINDOW_TEXT = "Invalid day/month/year entry."
DATE_ENTRY_NOT_VALID_WINDOW_BUTTON_TEXT = "OK"